const httpStatus = require('http-status');

const ERROR_TYPES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  DUPLICATE_ERROR: 'DUPLICATE_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR'
};

const ERROR_MESSAGES = {
  [ERROR_TYPES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_TYPES.AUTHENTICATION_ERROR]: 'Authentication failed',
  [ERROR_TYPES.AUTHORIZATION_ERROR]: 'Access denied',
  [ERROR_TYPES.NOT_FOUND_ERROR]: 'Resource not found',
  [ERROR_TYPES.DUPLICATE_ERROR]: 'Resource already exists',
  [ERROR_TYPES.RATE_LIMIT_ERROR]: 'Too many requests',
  [ERROR_TYPES.EXTERNAL_SERVICE_ERROR]: 'External service unavailable',
  [ERROR_TYPES.DATABASE_ERROR]: 'Database operation failed',
  [ERROR_TYPES.FILE_UPLOAD_ERROR]: 'File upload failed',
  [ERROR_TYPES.BUSINESS_LOGIC_ERROR]: 'Business rule violation'
};

const ERROR_STATUS_CODES = {
  [ERROR_TYPES.VALIDATION_ERROR]: httpStatus.BAD_REQUEST,
  [ERROR_TYPES.AUTHENTICATION_ERROR]: httpStatus.UNAUTHORIZED,
  [ERROR_TYPES.AUTHORIZATION_ERROR]: httpStatus.FORBIDDEN,
  [ERROR_TYPES.NOT_FOUND_ERROR]: httpStatus.NOT_FOUND,
  [ERROR_TYPES.DUPLICATE_ERROR]: httpStatus.CONFLICT,
  [ERROR_TYPES.RATE_LIMIT_ERROR]: httpStatus.TOO_MANY_REQUESTS,
  [ERROR_TYPES.EXTERNAL_SERVICE_ERROR]: httpStatus.SERVICE_UNAVAILABLE,
  [ERROR_TYPES.DATABASE_ERROR]: httpStatus.INTERNAL_SERVER_ERROR,
  [ERROR_TYPES.FILE_UPLOAD_ERROR]: httpStatus.BAD_REQUEST,
  [ERROR_TYPES.BUSINESS_LOGIC_ERROR]: httpStatus.UNPROCESSABLE_ENTITY
};

module.exports = {
  ERROR_TYPES,
  ERROR_MESSAGES,
  ERROR_STATUS_CODES
};